actions remake

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -18,8 +18,8 @@ jobs:
       
     - name: Build project
       run: |
-      cd src  
-      make
+       cd src  
+       make
 
   style-check:
     runs-on: ubuntu-latest
@@ -31,12 +31,12 @@ jobs:
       
     - name: Check code style
       run: |
-      cd src  
-      output=$(make style-check 2>&1)
-        if [ $? -eq 0 ]; then
-          echo -e "\e[32mclang-format check passed\e[0m"
-        else
-          echo -e "\e[31mclang-format check failed\e[0m"
-          echo "$output"
-          exit 1
-        fi
+       cd src  
+       output=$(make style-check 2>&1)
+         if [ $? -eq 0 ]; then
+           echo -e "\e[32mclang-format check passed\e[0m"
+         else
+           echo -e "\e[31mclang-format check failed\e[0m"
+           echo "$output"
+           exit 1
+         fi
